import { StyleSheet } from "@react-pdf/renderer";

export const colors = {
  primary: "#7a5a2c",
  text: "#1a1a1a",
  muted: "#6b6356",
  border: "#dcd6cc",
  bg: "#ffffff",
  alt: "#faf8f4",
};

export const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: colors.text,
    backgroundColor: colors.bg,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 16,
    marginBottom: 24,
  },
  brand: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.primary,
    fontFamily: "Helvetica-Bold",
  },
  brandSub: {
    fontSize: 9,
    color: colors.muted,
    marginTop: 2,
  },
  metaRight: { textAlign: "right" },
  docTitle: {
    fontSize: 16,
    fontWeight: 700,
    fontFamily: "Helvetica-Bold",
  },
  docNumber: {
    fontSize: 11,
    color: colors.muted,
    marginTop: 2,
  },
  twoCol: { flexDirection: "row", gap: 16, marginBottom: 16 },
  col: { flex: 1 },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    color: colors.muted,
    marginBottom: 4,
  },
  body: { fontSize: 10, lineHeight: 1.5 },
  bold: { fontFamily: "Helvetica-Bold", fontWeight: 700 },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 12,
  },
  table: { marginTop: 8 },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 6,
    marginBottom: 6,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.border,
  },
  th: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    color: colors.muted,
    letterSpacing: 0.4,
  },
  td: { fontSize: 10 },
  totalsBox: {
    marginTop: 16,
    alignSelf: "flex-end",
    width: 240,
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  totalsRowEmphasis: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  signatureBox: {
    marginTop: 32,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 4,
    backgroundColor: colors.alt,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: colors.muted,
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
  },
});
